name: Importar Planilhas Diárias para MongoDB

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente às 00:00 UTC (21:00 -03)
  workflow_dispatch:  # Permite execução manual

jobs:
  import-planilhas:
    runs-on: ubuntu-latest

    steps:
      # Clonar o repositório
      - name: Checkout código
        uses: actions/checkout@v4

      # Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Executar script de importação
      - name: Executar import_planilhas.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python import_planilhas.py

